test: replace cmocka assert_in_range with assert_uint_in_range
suppress warnings seen after updating cmocka 1.1.7 -> 2.0.1
(homebrew installs this version now.)

```
 /Users/runner/work/toywasm/toywasm/test/test.c:478:9: error: 'cmocka_macro' is deprecated: assert_in_range: use assert_int_in_range or assert_uint_in_range instead [-Werror,-Wdeprecated-declarations]
        assert_in_range(id, 1, 3);
        ^
/opt/homebrew/include/cmocka.h:5345:9: note: expanded from macro 'assert_in_range'
        CMOCKA_DEPRECATION_WARNING(                          \
        ^
/opt/homebrew/include/cmocka.h:219:9: note: expanded from macro 'CMOCKA_DEPRECATION_WARNING'
        cmocka_macro cmocka_deprecated_var __attribute__((unused)) = 0; \
        ^
/Users/runner/work/toywasm/toywasm/test/test.c:478:9: note: 'cmocka_macro' has been explicitly marked deprecated here
/opt/homebrew/include/cmocka.h:5345:9: note: expanded from macro 'assert_in_range'
        CMOCKA_DEPRECATION_WARNING(                          \
        ^
/opt/homebrew/include/cmocka.h:218:49: note: expanded from macro 'CMOCKA_DEPRECATION_WARNING'
        typedef int cmocka_macro __attribute__((deprecated(msg)));      \
                                                ^
```